version: '2'
services:
    ims1-app:
        image: ims1
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ims1-postgresql:5432/IMS1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ims1-postgresql:
        extends:
            file: postgresql.yml
            service: ims1-postgresql
